### ISSUE TITLE
Way to batch convert in pandas without multiple API requests?

### ISSUE THREAD

**Issue by tadisdef** [what3words/w3w-python-wrapper#14]
Hello!

I have been working with converting what3words addresses to coordinates using python inside the software Alteryx. Alteryx converts my excel file (with a column of What3Words addresses) to a pandas dataframe and then I use this wrapper and for loop to convert each of them. Is there a way to batch out the whole column without using tons of API requests?

Asking because I made 104 API requests in my trial and error phase yesterday.

**Comment by ManuCiao** [comment]
Unfortunately, the what3words API does not offer a batch processing endpoint to convert multiple addresses in a single API call, but there are strategies to minimise unnecessary API calls.

Strategies to Reduce API Requests:

**1. Cache API Results:**
 - If your data contains duplicate what3words addresses, you can cache the results and reuse them instead of making redundant API requests.
 - Use a dictionary to store previously queried what3words addresses and their coordinates.

**2. Check for Duplicates Before Sending Requests:**
 - Before sending a request for each address in the DataFrame, check if the same address has already been queried. If yes, use the stored result instead of making another API request.
